---
to: src/components/templatingComponents/<%= componentType %>/<%= h.changeCase.pascal(name) %>/index.tsx
---
import React from 'react';
import styles from './index.module.scss';

// Ajoutez vos props ici
// Exemple: interface <%= h.changeCase.pascal(name) %>Props extends Record<string, unknown> {
//   title?: string;
// }
type <%= h.changeCase.pascal(name) %>Props = Record<string, unknown>;

export default function <%= h.changeCase.pascal(name) %>({}: <%= h.changeCase.pascal(name) %>Props) {
  return (
    <div className={styles.main}>
      Generated by Hygen script in src/components/templatingComponents/<%= componentType %>/<%= h.changeCase.pascal(name) %>/index.tsx
    </div>
  );
}
