---
to: src/components/<%= h.changeCase.pascal(name) %>/index.tsx
---
import styles from './index.module.scss';

export type <%= h.changeCase.pascal(name) %>Type = {
  mapWidth: number
  mapHeight: number
}

export default function <%= h.changeCase.pascal(name) %>({ mapWidth, mapHeight }: <%= h.changeCase.pascal(name) %>Type ) {
  return (
    <div className={styles.main}>
      Generated by Hygen script in src/components/<%= h.changeCase.pascal(name) %>/index.tsx
    </div>
  );
}