import React from 'react';
import styles from './index.module.scss';

// Ajoutez vos props ici
// Exemple: interface Test1Props extends Record<string, unknown> {
//   title?: string;
// }
type Test1Props = Record<string, unknown>;

export default function Test1({}: Test1Props) {
  return (
    <div className={styles.main}>
      Generated by Hygen script in src/components/templatingComponents/page/Test1/index.tsx
    </div>
  );
}
