import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/styles/global.scss';
import '@/styles/reset.scss';
import ReduxProvider from './ReduxProvider';
import CursorProvider from './CursorProvider';
import Header from './Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const announcements = [
  {
    color: "green",
    text: "Availaible for freelance work"
  }
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <CursorProvider>
            <Header announcements={announcements}/>
            {children}
          </CursorProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
