import type { Metadata } from "next";
import '@/styles/global.scss';
import '@/styles/reset.scss';
import ReduxProvider from '@/contexts/ReduxContext';
import CursorProvider from '@/contexts/CursorContext';
import { ModalProvider } from '@/contexts/ModalContext';
import { TemplatingProvider } from '@/contexts/TemplatingContext';
import { ScrollContextProvider } from '@/contexts/ScrollContext';
import Header from '@/components/app/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ReduxProvider>
          <CursorProvider>
            <ModalProvider>
              <TemplatingProvider>
                <ScrollContextProvider>
                  <Header />
                  {children}
                </ScrollContextProvider>
              </TemplatingProvider>
            </ModalProvider>
          </CursorProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
