import React from 'react';
import styles from './index.module.scss';

// Ajoutez vos props ici
// Exemple: interface TestProps extends Record<string, unknown> {
//   title?: string;
// }
type TestProps = Record<string, unknown>;

export default function Test({}: TestProps) {
  return (
    <div className={styles.main}>
      Generated by Hygen script in src/components/templatingComponents/page/Test/index.tsx
    </div>
  );
}
